/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inosystem.pdv.view;

import controller.ControllerFormaPagamento;
import controller.ControllerPermissaousuario;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import model.ModelFormaPagamento;
import model.ModelSessaoUsuario;
import util.BLMascaras;

/**
 *
 * @author Jrpbjr
 */
public class ViewPagamentoPDV extends javax.swing.JDialog {

    private float valorTotal;
    private float desconto;
    private float valorRecebido;
    private float troco;
    private float totalPagar;
    private float valorCusto;
    private float dinheiro;
    private float cartao;
    private float cheque;
    private float convenio;
    private String tipoPagamento;
    ControllerFormaPagamento controllerTipoPagamento = new ControllerFormaPagamento();
    ArrayList<ModelFormaPagamento> listaModelTipoPagamentos = new ArrayList<>();
    private ViewVerificarPermissao viewVerificarPermissao;

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form ViewPagamentoPDV
     */
    public ViewPagamentoPDV(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.viewVerificarPermissao = new ViewVerificarPermissao(null, true);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlRS = new javax.swing.JLabel();
        jlfValorPagar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfTroco = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfDinheiro = new javax.swing.JTextField();
        jtfCartao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfCheque = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfConvenio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfValorRecebido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfSubtotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfDesconto = new javax.swing.JTextField();

        setTitle("Pagamento");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/blicon.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 30/icons8-selecionado-filled-50.png"))); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total a pagar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jlRS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlRS.setForeground(new java.awt.Color(0, 153, 102));
        jlRS.setText("R$");

        jlfValorPagar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlfValorPagar.setForeground(new java.awt.Color(0, 153, 102));
        jlfValorPagar.setText("valor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jlRS)
                .addGap(56, 56, 56)
                .addComponent(jlfValorPagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRS)
                    .addComponent(jlfValorPagar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Troco:");

        jtfTroco.setEditable(false);
        jtfTroco.setBackground(new java.awt.Color(255, 204, 204));
        jtfTroco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTrocoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de pagamento"));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Dinheiro");

        jtfDinheiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDinheiroKeyReleased(evt);
            }
        });

        jtfCartao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCartaoKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Cartão");

        jtfCheque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfCheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfChequeKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Cheque");

        jtfConvenio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfConvenio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfConvenioKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Convênio");

        jtfValorRecebido.setEditable(false);
        jtfValorRecebido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfValorRecebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfValorRecebidoFocusLost(evt);
            }
        });
        jtfValorRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfValorRecebidoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Total recebido:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtfCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jtfConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Valor total:");

        jtfSubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfSubtotal.setText("0.0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Desconto:");

        jtfDesconto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDescontoFocusLost(evt);
            }
        });
        jtfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDescontoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfSubtotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTroco)
                        .addGap(18, 18, 18)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfSubtotal)
                    .addComponent(jLabel11)
                    .addComponent(jtfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel6))
                        .addComponent(jtfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(okButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        //verifica se o valor recebido é o suficiente para pagar
        float ptroco;
        try {
            this.desconto = Float.parseFloat(this.jtfDesconto.getText());
        } catch (Exception e) {
            this.desconto = 0;
        }
        try {
            this.valorRecebido = Float.parseFloat(this.jtfValorRecebido.getText());
        } catch (Exception e) {
            this.valorRecebido = 0;
        }
        try {
            this.cartao = Float.parseFloat(this.jtfCartao.getText());
        } catch (Exception e) {
            this.cartao = 0;
        }
        try {
            this.cheque = Float.parseFloat(this.jtfCheque.getText());
        } catch (Exception e) {
            this.cheque = 0;
        }
        try {
            this.convenio = Float.parseFloat(this.jtfConvenio.getText());
        } catch (Exception e) {
            convenio = 0;
        }
        try {
            this.dinheiro = Float.parseFloat(this.jtfDinheiro.getText());
        } catch (Exception e) {
            dinheiro = 0;
        }
        try {
            ptroco = Float.parseFloat(jtfTroco.getText());
            if (ptroco < 0) {
                JOptionPane.showMessageDialog(null, "Valor recebido não é o suficiente para pagar a venda!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            } else {
                this.troco = ptroco;
                this.totalPagar = Float.parseFloat(this.jlfValorPagar.getText());
                this.tipoPagamento = "A vista";
                this.dinheiro = dinheiro - troco;
                doClose(RET_OK);
            }
        } catch (Exception e) {
            ptroco = 0;
            JOptionPane.showMessageDialog(null, "Informe o valor pago!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jtfTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTrocoActionPerformed

    private void jtfValorRecebidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfValorRecebidoFocusLost
        // TODO add your handling code here:
        this.jlfValorPagar.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularDesconto()) + "");
        this.jtfTroco.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularTroco()) + "");
    }//GEN-LAST:event_jtfValorRecebidoFocusLost

    private void jtfValorRecebidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorRecebidoKeyReleased
        // TODO add your handling code here:
        this.jtfValorRecebido.setText(new BLMascaras().converterVirgulaParaPonto(this.jtfValorRecebido.getText()));
    }//GEN-LAST:event_jtfValorRecebidoKeyReleased

    private void jtfDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDescontoFocusLost
        // TODO add your handling code here:
        this.jlfValorPagar.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularDesconto()) + "");
        this.jtfTroco.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularTroco()) + "");
    }//GEN-LAST:event_jtfDescontoFocusLost

    private void jtfDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoKeyReleased
        // TODO add your handling code here:
        this.jtfDesconto.setText(new BLMascaras().converterVirgulaParaPonto(this.jtfDesconto.getText()));
    }//GEN-LAST:event_jtfDescontoKeyReleased

    private void jtfDinheiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDinheiroKeyReleased
        // TODO add your handling code here:
        this.jtfValorRecebido.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularValorRecebido()) + "");
        this.jtfTroco.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularTroco()) + "");
    }//GEN-LAST:event_jtfDinheiroKeyReleased

    private void jtfCartaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCartaoKeyReleased
        // TODO add your handling code here:
        this.jtfValorRecebido.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularValorRecebido()) + "");
        this.jtfTroco.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularTroco()) + "");
    }//GEN-LAST:event_jtfCartaoKeyReleased

    private void jtfChequeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfChequeKeyReleased
        // TODO add your handling code here:
        this.jtfValorRecebido.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularValorRecebido()) + "");
        this.jtfTroco.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularTroco()) + "");
    }//GEN-LAST:event_jtfChequeKeyReleased

    private void jtfConvenioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfConvenioKeyReleased
        // TODO add your handling code here:
        this.jtfValorRecebido.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularValorRecebido()) + "");
        this.jtfTroco.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.calcularTroco()) + "");
    }//GEN-LAST:event_jtfConvenioKeyReleased

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    //verificar permissão do usuário
    public boolean retornarCodigoUsuarioLogado() {
        try {
            String permissao = new ControllerPermissaousuario().getPermissaousuarioCodUsuController(new ModelSessaoUsuario().codigo).getPermissao();
            if (permissao.equals("compras")) {
                return true;
            } else {
                return false;
            }
        } catch (Exception e) {
            return false;
        }
    }

    private float calcularValorRecebido() {
        float pdinheiro, pcartao, pcheque, pconvenio = 0;
        if (this.jtfDinheiro.getText().equals("")) {
            pdinheiro = 0;
        } else {
            pdinheiro = Float.parseFloat(this.jtfDinheiro.getText());
        }
        if (this.jtfCartao.getText().equals("")) {
            pcartao = 0;
        } else {
            pcartao = Float.parseFloat(this.jtfCartao.getText());
        }
        if (this.jtfCheque.getText().equals("")) {
            pcheque = 0;
        } else {
            pcheque = Float.parseFloat(this.jtfCheque.getText());
        }
        if (this.jtfConvenio.getText().equals("")) {
            pconvenio = 0;
        } else {
            pconvenio = Float.parseFloat(this.jtfConvenio.getText());
        }
        return pdinheiro + pcartao + pcheque + pconvenio;
    }

    private float calcularDesconto() {
        float pSubTotal, pDesconto = 0;
        if (this.jtfSubtotal.getText().equals("")) {
            pSubTotal = 0;
        } else {
            pSubTotal = Float.parseFloat(this.jtfSubtotal.getText());
        }
        if (this.jtfDesconto.getText().equals("")) {
            pDesconto = 0;
        } else {
            pDesconto = Float.parseFloat(this.jtfDesconto.getText());
        }
        valorTotal = pSubTotal - pDesconto;
        return valorTotal;
    }

    private float calcularTroco() {
        float pValorRecebid = 0;
        if (this.jtfValorRecebido.getText().equals("")) {
            pValorRecebid = 0;
        } else {
            pValorRecebid = Float.parseFloat(this.jtfValorRecebido.getText());
        }
        return pValorRecebid - valorTotal;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewPagamentoPDV dialog = new ViewPagamentoPDV(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlRS;
    private javax.swing.JLabel jlfValorPagar;
    private javax.swing.JTextField jtfCartao;
    private javax.swing.JTextField jtfCheque;
    private javax.swing.JTextField jtfConvenio;
    private javax.swing.JTextField jtfDesconto;
    private javax.swing.JTextField jtfDinheiro;
    private javax.swing.JLabel jtfSubtotal;
    private javax.swing.JTextField jtfTroco;
    private javax.swing.JTextField jtfValorRecebido;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;

    /**
     * @return the valorTotal
     */
    public float getValorTotal() {
        return valorTotal;
    }

    /**
     * @param valorTotal the valorTotal to set
     */
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }

    public void setTextFildValorTotal() {
        //setar valor total
        this.jtfSubtotal.setText(new BLMascaras().arredondamentoComPontoDuasCasas(this.valorTotal) + "");
        jlfValorPagar.setText(jtfSubtotal.getText());
        //limpar interface
        jtfDesconto.setText("0");
        jtfDinheiro.setText("0");
        jtfCartao.setText("0");
        jtfCheque.setText("0");
        jtfConvenio.setText("0");
        jtfValorRecebido.setText("0");
        jtfDinheiro.requestFocus();
    }

    /**
     * @return the desconto
     */
    public float getDesconto() {
        return desconto;
    }

    /**
     * @param desconto the desconto to set
     */
    public void setDesconto(float desconto) {
        this.desconto = desconto;
    }

    /**
     * @return the valorRecebido
     */
    public float getValorRecebido() {
        return valorRecebido;
    }

    /**
     * @param valorRecebido the valorRecebido to set
     */
    public void setValorRecebido(float valorRecebido) {
        this.valorRecebido = valorRecebido;
    }

    /**
     * @return the troco
     */
    public float getTroco() {
        return troco;
    }

    /**
     * @param troco the troco to set
     */
    public void setTroco(float troco) {
        this.troco = troco;
    }

    /**
     * @return the totalPagar
     */
    public float getTotalPagar() {
        return totalPagar;
    }

    /**
     * @param totalPagar the totalPagar to set
     */
    public void setTotalPagar(float totalPagar) {
        this.totalPagar = totalPagar;
    }

    /**
     * @return the tipoPagamento
     */
    public String getTipoPagamento() {
        return tipoPagamento;
    }

    /**
     * @param tipoPagamento the tipoPagamento to set
     */
    public void setTipoPagamento(String tipoPagamento) {
        this.tipoPagamento = tipoPagamento;
    }

    /**
     * @return the valorCusto
     */
    public float getValorCusto() {
        return valorCusto;
    }

    /**
     * @param valorCusto the valorCusto to set
     */
    public void setValorCusto(float valorCusto) {
        this.valorCusto = valorCusto;
    }

    /**
     * @return the dinheiro
     */
    public float getDinheiro() {
        return dinheiro;
    }

    /**
     * @param dinheiro the dinheiro to set
     */
    public void setDinheiro(float dinheiro) {
        this.dinheiro = dinheiro;
    }

    /**
     * @return the cartao
     */
    public float getCartao() {
        return cartao;
    }

    /**
     * @param cartao the cartao to set
     */
    public void setCartao(float cartao) {
        this.cartao = cartao;
    }

    /**
     * @return the cheque
     */
    public float getCheque() {
        return cheque;
    }

    /**
     * @param cheque the cheque to set
     */
    public void setCheque(float cheque) {
        this.cheque = cheque;
    }

    /**
     * @return the convenio
     */
    public float getConvenio() {
        return convenio;
    }

    /**
     * @param convenio the convenio to set
     */
    public void setConvenio(float convenio) {
        this.convenio = convenio;
    }
}
