package com.inosystem.pdv.view;

import com.inosystem.pdv.contoller.CidadeController;
import com.inosystem.pdv.contoller.EmpresaCidadeEstadoController;
import com.inosystem.pdv.contoller.EmpresaController;
import com.inosystem.pdv.contoller.EstadoController;
import com.inosystem.pdv.model.Cidade;
import com.inosystem.pdv.model.Empresa;
import com.inosystem.pdv.model.EmpresaCidadeEstado;
import com.inosystem.pdv.model.Estado;
import com.inosystem.pdv.util.Mascara;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Jrpbjr * jrpbjr *
 */
public class ViewEmpresa extends javax.swing.JFrame {

    Empresa modelEmpresa = new Empresa();
    EmpresaController controllerEmpresa = new EmpresaController();
    EstadoController EstadoController = new EstadoController();
    CidadeController controllerCidade = new CidadeController();
    EmpresaCidadeEstadoController controllerEmpresaCidadeEstado = new EmpresaCidadeEstadoController();
    ArrayList<Cidade> listaCidades = new ArrayList<>();
    ArrayList<Estado> listaEstados = new ArrayList<>();
    ArrayList<Empresa> listaEmpresas = new ArrayList<>();
    ArrayList<EmpresaCidadeEstado> listaEmpresaCidadeEstados = new ArrayList<>();
    EmpresaCidadeEstado modelEmpresaCidadeEstado = new EmpresaCidadeEstado();
    Mascara bLMascaras = new Mascara();

    /**
     * Creates new form Empresas
     */
    public ViewEmpresa() {
        initComponents();
        setLocationRelativeTo(null);
        this.carregarEmpresa();
        this.listarEstados();
        this.listarCidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNomeFantasia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btAlterar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpresa = new javax.swing.JTable();
        tfCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox();
        cbCidade = new javax.swing.JComboBox();
        btNovaCidade = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfRazaoSocial = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfLogomarca = new javax.swing.JTextField();
        btLocalizarImagem = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfInscricaoEstadual = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfPais = new javax.swing.JTextField();
        jtfCrt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfCNPJ = new javax.swing.JFormattedTextField();
        tfCep = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empresa");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/blicon.png")).getImage());
        setResizable(false);

        jLabel1.setText("Nome fantasia:");

        tfNomeFantasia.setEditable(false);
        tfNomeFantasia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNomeFantasiaFocusLost(evt);
            }
        });

        jLabel2.setText("Endereço:");

        tfEndereco.setEditable(false);
        tfEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEnderecoFocusLost(evt);
            }
        });

        tfBairro.setEditable(false);
        tfBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfBairroFocusLost(evt);
            }
        });

        jLabel3.setText("Bairro:");

        jLabel4.setText("Cidade:");

        jLabel5.setText("UF:");

        jLabel6.setText("CEP:");

        tfTelefone.setEditable(false);

        jLabel7.setText("Telefone:");

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-editar-filled-50.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-fechar-janela-filled-50.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-salvar-filled-50.png"))); // NOI18N
        btSalvar.setText("Salvar alteração");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        tblEmpresa.setAutoCreateRowSorter(true);
        tblEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cidade", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmpresa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblEmpresa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEmpresa.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblEmpresa);
        if (tblEmpresa.getColumnModel().getColumnCount() > 0) {
            tblEmpresa.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblEmpresa.getColumnModel().getColumn(2).setMinWidth(150);
            tblEmpresa.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblEmpresa.getColumnModel().getColumn(3).setMinWidth(150);
            tblEmpresa.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        tfCodigo.setEditable(false);
        tfCodigo.setEnabled(false);

        jLabel8.setText("Código:");

        cbEstado.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbEstadoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btNovaCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-adicionar-filled-50.png"))); // NOI18N
        btNovaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovaCidadeActionPerformed(evt);
            }
        });

        jLabel9.setText("Razão social:");

        tfRazaoSocial.setEditable(false);
        tfRazaoSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfRazaoSocialFocusLost(evt);
            }
        });

        jLabel10.setText("Logomarca:");

        tfLogomarca.setEditable(false);
        tfLogomarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfLogomarca.setForeground(new java.awt.Color(255, 0, 0));
        tfLogomarca.setText("TAMANHO IDEAL 323X80");

        btLocalizarImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-binóculos-filled-50.png"))); // NOI18N
        btLocalizarImagem.setText("Localizar Logo");
        btLocalizarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocalizarImagemActionPerformed(evt);
            }
        });

        jLabel11.setText("CNPJ");

        jtfNumero.setEnabled(false);

        jLabel12.setText("Numero:");

        jtfComplemento.setEnabled(false);
        jtfComplemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfComplementoFocusLost(evt);
            }
        });

        jLabel13.setText("Completo:");

        jtfInscricaoEstadual.setEnabled(false);

        jLabel14.setText("Inscrição estadual:");

        jLabel15.setText("Código pais:");

        jtfPais.setText("1058");
        jtfPais.setEnabled(false);

        jtfCrt.setEnabled(false);

        jLabel16.setText("CRT:");

        tfCNPJ.setEditable(false);
        try {
            tfCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCep.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLogomarca, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLocalizarImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCancelar)
                        .addGap(11, 11, 11)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(tfNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1)
                                .addGap(240, 240, 240)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jtfCrt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(159, 159, 159)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPais))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(186, 186, 186)
                                .addComponent(jLabel12)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel13)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(8, 8, 8)
                                .addComponent(btNovaCidade)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBairro)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel16)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfCrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel11)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel12)
                        .addComponent(jLabel3)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btNovaCidade))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLogomarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLocalizarImagem)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancelar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAlterar)
                        .addComponent(btSalvar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.desabilitarCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * Preencher combobox estados
     */
    private void listarEstados() {
        listaEstados = EstadoController.getListaEstadoController();
        cbEstado.removeAllItems();
        for (int i = 0; i < listaEstados.size(); i++) {
            cbEstado.addItem(listaEstados.get(i).getUf());
        }
    }

    /**
     * Preencher combobox cidades
     */
    private void listarCidades() {
        listaCidades = controllerCidade.getListaCidadePorEstadoController(EstadoController.getEstadoUFController(this.cbEstado.getSelectedItem().toString()).getCodigo());
        cbCidade.removeAllItems();
        for (int i = 0; i < listaCidades.size(); i++) {
            cbCidade.addItem(listaCidades.get(i).getNome());
        }
    }

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        novo();
        habilitarCampos();
        recuperarEmpresa();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        alterarEmpresa();
    }//GEN-LAST:event_btSalvarActionPerformed

    private boolean alterarEmpresa() {
        modelEmpresa.setCodigo(Integer.parseInt(this.tfCodigo.getText()));
        modelEmpresa.setNomeFantasia(this.tfNomeFantasia.getText());
        modelEmpresa.setRazaoSocial(this.tfRazaoSocial.getText());
        modelEmpresa.setCnpj(this.tfCNPJ.getText());
        modelEmpresa.setEndereco(this.tfEndereco.getText());
        modelEmpresa.setEnderecoNumero(this.jtfNumero.getText());
        modelEmpresa.setEnderecoComplemento(this.jtfComplemento.getText());
        modelEmpresa.setBairro(this.tfBairro.getText());
        modelEmpresa.setCodCidade(controllerCidade.getCidadeController(this.cbCidade.getSelectedItem().toString()).getCodigo());
        modelEmpresa.setCodPais(Integer.parseInt(jtfPais.getText()));
        modelEmpresa.setCep(this.tfCep.getText());
        modelEmpresa.setTelefone(this.tfTelefone.getText());
        modelEmpresa.setInscEstad(this.jtfInscricaoEstadual.getText());
        modelEmpresa.setCrt(this.jtfCrt.getText());

        //alterar 
        if (controllerEmpresa.atualizarEmpresaController(modelEmpresa)) {
            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
            this.desabilitarCampos();
            this.carregarEmpresa();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean recuperarEmpresa() {
        //pega o codigo da linha selecionada
        int codigo = (Integer) tblEmpresa.getValueAt(0, 0);

        try {
            //recupera os dados do banco
            modelEmpresaCidadeEstado = controllerEmpresa.getEmpresaController(codigo);
            //seta os dados na interface
            this.tfCodigo.setText(String.valueOf(modelEmpresaCidadeEstado.getEmpresa().getCodigo()));
            this.tfRazaoSocial.setText(modelEmpresaCidadeEstado.getEmpresa().getRazaoSocial());
            this.jtfInscricaoEstadual.setText(modelEmpresaCidadeEstado.getEmpresa().getInscEstad());
            this.jtfCrt.setText(modelEmpresaCidadeEstado.getEmpresa().getCrt());
            this.tfNomeFantasia.setText(modelEmpresaCidadeEstado.getEmpresa().getNomeFantasia());
            this.tfCNPJ.setText(modelEmpresaCidadeEstado.getEmpresa().getCnpj());
            this.jtfPais.setText(modelEmpresaCidadeEstado.getEmpresa().getCodPais() + "");
            this.tfEndereco.setText(modelEmpresaCidadeEstado.getEmpresa().getEndereco());
            this.jtfNumero.setText(modelEmpresaCidadeEstado.getEmpresa().getEnderecoNumero());
            this.jtfComplemento.setText(modelEmpresaCidadeEstado.getEmpresa().getEnderecoComplemento());
            this.tfBairro.setText(modelEmpresaCidadeEstado.getEmpresa().getBairro());
            this.cbEstado.setSelectedItem(EstadoController.getEstadoController(modelEmpresaCidadeEstado.getEstado().getUf()));
            this.listarCidades();
            this.cbCidade.setSelectedItem(controllerCidade.getCidadeController(modelEmpresaCidadeEstado.getCidade().getNome()));
            this.tfCep.setText(modelEmpresaCidadeEstado.getEmpresa().getCep());
            this.tfTelefone.setText(modelEmpresaCidadeEstado.getEmpresa().getTelefone());
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    private void carregarEmpresa() {
        modelEmpresaCidadeEstado = controllerEmpresaCidadeEstado.getEmpresaCidadeEstadoController(1);
        DefaultTableModel modelo = (DefaultTableModel) tblEmpresa.getModel();
        modelo.setNumRows(0);
        //CARREGA OS DADOS DA LISTA NA TABELA
        modelo.addRow(new Object[]{
            modelEmpresaCidadeEstado.getEmpresa().getCodigo(),
            modelEmpresaCidadeEstado.getEmpresa().getNomeFantasia(),
            modelEmpresaCidadeEstado.getCidade().getNome(),
            modelEmpresaCidadeEstado.getEstado().getUf()
        });
    }

    private void novo() {
        habilitarCampos();
        tfCodigo.setText("Novo");
        tfNomeFantasia.setText("");
        tfRazaoSocial.setText("");
        tfEndereco.setText("");
        tfBairro.setText("");
        tfCep.setText("");
        tfTelefone.setText("");
        tfCNPJ.setText("");
    }

    protected boolean verificarCampos() {
        if (!tfNomeFantasia.getText().trim().equals("")) {
            return true;
        }
        return false;
    }

    private void habilitarCampos() {
        tfNomeFantasia.setEditable(true);
        tfRazaoSocial.setEditable(true);
        tfEndereco.setEditable(true);
        tfBairro.setEditable(true);
        cbCidade.setEnabled(true);
        tfCep.setEditable(true);
        cbEstado.setEnabled(true);
        tfTelefone.setEditable(true);
        tfCNPJ.setEditable(true);
        btSalvar.setEnabled(true);
        jtfCrt.setEnabled(true);
        jtfNumero.setEnabled(true);
        jtfComplemento.setEnabled(true);
        jtfPais.setEnabled(true);
        jtfInscricaoEstadual.setEnabled(true);
    }

    protected void desabilitarCampos() {
        tfNomeFantasia.setEditable(false);
        tfRazaoSocial.setEditable(true);
        tfEndereco.setEditable(false);
        tfBairro.setEditable(false);
        cbCidade.setEnabled(false);
        tfCep.setEditable(false);
        cbEstado.setEnabled(false);
        tfTelefone.setEditable(false);
        tfCNPJ.setEditable(false);
        btSalvar.setEnabled(false);
        jtfCrt.setEnabled(false);
        jtfNumero.setEnabled(false);
        jtfComplemento.setEnabled(false);
        jtfPais.setEnabled(false);
        jtfInscricaoEstadual.setEnabled(false);
        tfCodigo.setText("");
        tfNomeFantasia.setText("");
        tfRazaoSocial.setText("");
        tfEndereco.setText("");
        tfBairro.setText("");
        tfCep.setText("");
        tfTelefone.setText("");
        tfCNPJ.setText("");
    }


    private void tfNomeFantasiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomeFantasiaFocusLost
        // converte em maiusculo o que o usuario digitar
        this.tfNomeFantasia.setText(tfNomeFantasia.getText().toUpperCase());
        //tira acentos
        this.tfNomeFantasia.setText(bLMascaras.TiraAcentos(tfNomeFantasia.getText()));
    }//GEN-LAST:event_tfNomeFantasiaFocusLost

    private void cbEstadoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbEstadoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (this.cbEstado.isPopupVisible()) {
            listarCidades();
        }
    }//GEN-LAST:event_cbEstadoPopupMenuWillBecomeInvisible

    private void btNovaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovaCidadeActionPerformed
        // TODO add your handling code here:
        new ViewCidade().setVisible(true);
    }//GEN-LAST:event_btNovaCidadeActionPerformed

    private void btLocalizarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocalizarImagemActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(btLocalizarImagem);
            File file = chooser.getSelectedFile();

            String l = file.getAbsolutePath();
            //caminho da imagem e nome
            String caminhoImagem = "C:/BLVendas/src/imagens/processimg.png";

            FileInputStream fisDe = new FileInputStream(l);
            FileOutputStream fisPara = new FileOutputStream(caminhoImagem);

            FileChannel fcPara = fisDe.getChannel();
            FileChannel fcDe = fisPara.getChannel();
            tfLogomarca.setText(caminhoImagem);

            if (fcPara.transferTo(0, fcPara.size(), fcDe) == 0L) {
                fcPara.close();
                fcDe.close();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btLocalizarImagemActionPerformed

    private void tfRazaoSocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRazaoSocialFocusLost
        // converte em maiusculo o que o usuario digitar
        this.tfRazaoSocial.setText(tfRazaoSocial.getText().toUpperCase());
        //tira acentos
        this.tfRazaoSocial.setText(bLMascaras.TiraAcentos(tfRazaoSocial.getText()));
    }//GEN-LAST:event_tfRazaoSocialFocusLost

    private void tfEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEnderecoFocusLost
        // converte em maiusculo o que o usuario digitar
        this.tfEndereco.setText(tfEndereco.getText().toUpperCase());
        //tira acentos
        this.tfEndereco.setText(bLMascaras.TiraAcentos(tfEndereco.getText()));
    }//GEN-LAST:event_tfEnderecoFocusLost

    private void jtfComplementoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfComplementoFocusLost
        // converte em maiusculo o que o usuario digitar
        this.jtfComplemento.setText(jtfComplemento.getText().toUpperCase());
        //tira acentos
        this.jtfComplemento.setText(bLMascaras.TiraAcentos(jtfComplemento.getText()));
    }//GEN-LAST:event_jtfComplementoFocusLost

    private void tfBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBairroFocusLost
        // converte em maiusculo o que o usuario digitar
        this.tfBairro.setText(tfBairro.getText().toUpperCase());
        //tira acentos
        this.tfBairro.setText(bLMascaras.TiraAcentos(tfBairro.getText()));
    }//GEN-LAST:event_tfBairroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btLocalizarImagem;
    private javax.swing.JButton btNovaCidade;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfCrt;
    private javax.swing.JTextField jtfInscricaoEstadual;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfPais;
    private javax.swing.JTable tblEmpresa;
    protected javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfCNPJ;
    private javax.swing.JFormattedTextField tfCep;
    private javax.swing.JTextField tfCodigo;
    protected javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfLogomarca;
    protected javax.swing.JTextField tfNomeFantasia;
    private javax.swing.JTextField tfRazaoSocial;
    protected javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

}
