/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.inosystem.pdv.view;


import com.inosystem.pdv.contoller.UnidadeMediaController;
import com.inosystem.pdv.model.UnidadeMedia;
import com.inosystem.pdv.util.Mascara;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Jrpbjr
 */
public class ViewUnidadeMedia extends javax.swing.JFrame {

    UnidadeMediaController controllerUnidadeMedia = new UnidadeMediaController();
    UnidadeMedia modelUnidadeMedia = new UnidadeMedia();
    ArrayList<UnidadeMedia> listaUnidadeMedias = new ArrayList<>();
    String tipoCadastro;
    Mascara bLMascaras = new Mascara();
    
    /**
     * Creates new form ViewUnidadeMedia
     */
    public ViewUnidadeMedia() {
        initComponents();
        novaUnidade();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfAbreviacao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jbLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUnidadeMedida = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unidade de Medida");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/blicon.png")).getImage());

        tfCodigo.setEditable(false);

        jLabel1.setText("Código");

        tfAbreviacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAbreviacaoFocusLost(evt);
            }
        });

        jLabel2.setText("Abreviação");

        jLabel3.setText("Descrição");

        tfDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDescricaoFocusLost(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-fechar-janela-filled-50.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-salvar-filled-50.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        tbUnidadeMedida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Abreviação", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUnidadeMedida.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbUnidadeMedida);
        if (tbUnidadeMedida.getColumnModel().getColumnCount() > 0) {
            tbUnidadeMedida.getColumnModel().getColumn(0).setMinWidth(80);
            tbUnidadeMedida.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbUnidadeMedida.getColumnModel().getColumn(0).setMaxWidth(80);
            tbUnidadeMedida.getColumnModel().getColumn(1).setMinWidth(80);
            tbUnidadeMedida.getColumnModel().getColumn(1).setPreferredWidth(80);
            tbUnidadeMedida.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-excluir-filled-50.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-editar-filled-50.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbLimpar)
                            .addGap(5, 5, 5)
                            .addComponent(btExcluir)
                            .addGap(7, 7, 7)
                            .addComponent(btAlterar)
                            .addGap(145, 145, 145)
                            .addComponent(btSalvar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(tfAbreviacao))
                            .addComponent(tfDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfAbreviacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLimpar)
                    .addComponent(btExcluir)
                    .addComponent(btAlterar)
                    .addComponent(btSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        novaUnidade();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int linhaSelecionada = tbUnidadeMedida.getSelectedRow();
        // Verificamos se existe realmente alguma linha selecionada
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um item na tabela antes de clicar no botão!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        } else {
            this.excluirUnidade();
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        int linhaSelecionada = tbUnidadeMedida.getSelectedRow();
        // Verificamos se existe realmente alguma linha selecionada
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um item na tabela antes de clicar no botão!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }else{
            recuperarUnidade();
            tipoCadastro = "alteracao";
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (tipoCadastro.equals("novo")) {
            salvarUnidade();
            carregarUnidadesMedidas();
        } else if (tipoCadastro.equals("alteracao")) {
            alterarUnidade();
            carregarUnidadesMedidas();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfAbreviacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAbreviacaoFocusLost
        // converte em maiusculo o que o usuario digitar
        this.tfAbreviacao.setText(tfAbreviacao.getText().toUpperCase());
        this.tfAbreviacao.setText(bLMascaras.TiraAcentos(tfAbreviacao.getText()));
    }//GEN-LAST:event_tfAbreviacaoFocusLost

    private void tfDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDescricaoFocusLost
        // converte em maiusculo o que o usuario digitar
        this.tfDescricao.setText(tfDescricao.getText().toUpperCase());
        this.tfDescricao.setText(bLMascaras.TiraAcentos(tfDescricao.getText()));
    }//GEN-LAST:event_tfDescricaoFocusLost

    private boolean salvarUnidade(){
        //setar os dados no model
        modelUnidadeMedia.setAbreviacao(this.tfAbreviacao.getText());
        modelUnidadeMedia.setDescricao(this.tfDescricao.getText());

        //salvar 
        if (controllerUnidadeMedia.salvarUnidadeMediaController(modelUnidadeMedia)>0) {
            JOptionPane.showMessageDialog(this, "Registro gravado com sucesso!");
            novaUnidade();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao gravar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private boolean alterarUnidade(){
        modelUnidadeMedia.setCodigo(Integer.parseInt(this.tfCodigo.getText()));
        modelUnidadeMedia.setAbreviacao(this.tfAbreviacao.getText());
        modelUnidadeMedia.setDescricao(this.tfDescricao.getText());
        //salvar 
        if (controllerUnidadeMedia.atualizarUnidadeMediaController(modelUnidadeMedia)) {
            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
            novaUnidade();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    //recuperar os dados para a interface
    private boolean recuperarUnidade() {
        //recebe a linha selecionada
        int linha = this.tbUnidadeMedida.getSelectedRow();
        //pega o codigo do cliente na linha selecionada
        int codigo = (Integer) tbUnidadeMedida.getValueAt(linha, 0);
        try {
            //recupera os dados do banco
            modelUnidadeMedia = controllerUnidadeMedia.getUnidadeMediaController(codigo);
            //seta os dados na interface
            this.tfCodigo.setText(String.valueOf(modelUnidadeMedia.getCodigo()));
            this.tfAbreviacao.setText(modelUnidadeMedia.getAbreviacao());
            this.tfDescricao.setText(modelUnidadeMedia.getDescricao());
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
    
    private void excluirUnidade(){
        int linha = tbUnidadeMedida.getSelectedRow();
        String nome = (String) tbUnidadeMedida.getValueAt(linha, 2);
        int codigo = (Integer) tbUnidadeMedida.getValueAt(linha, 0);
        //pegunta se realmente deseja excluir
        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja"
                + " excluir o registro \nNome: "
                + nome + " ?", "Atenção", JOptionPane.YES_NO_OPTION);
        //se sim exclui, se não não faz nada    
        if (opcao == JOptionPane.OK_OPTION) {
            if (controllerUnidadeMedia.excluirUnidadeMediaController(codigo)) {
                JOptionPane.showMessageDialog(this, "Registro excluido com suscesso!");
                carregarUnidadesMedidas();
            }else{
            JOptionPane.showMessageDialog(this, "Erro ao e os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void novaUnidade(){
        tfCodigo.setText("Novo");
        tfAbreviacao.setText("");
        tfDescricao.setText("");
        tipoCadastro = "novo";
        carregarUnidadesMedidas();
    }
    
    
    /**
     * Carregar lista de unidade de medida na tabela
     */
    private void carregarUnidadesMedidas() {
        listaUnidadeMedias = controllerUnidadeMedia.getListaUnidadeMediaController();
        DefaultTableModel modelo = (DefaultTableModel) tbUnidadeMedida.getModel();
        modelo.setNumRows(0);
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listaUnidadeMedias.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaUnidadeMedias.get(i).getCodigo(),
                listaUnidadeMedias.get(i).getAbreviacao(),
                listaUnidadeMedias.get(i).getDescricao()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUnidadeMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUnidadeMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUnidadeMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUnidadeMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUnidadeMedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JTable tbUnidadeMedida;
    private javax.swing.JTextField tfAbreviacao;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDescricao;
    // End of variables declaration//GEN-END:variables
}
