package com.inosystem.pdv.view;

import com.inosystem.pdv.contoller.ProdutoController;
import com.inosystem.pdv.model.Produto;
import java.io.FileOutputStream;
import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.Image;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.BarcodeEAN;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jrpbjr
 */
public class ViewCodigobarras extends javax.swing.JFrame {

    ArrayList<Produto> listaProduto = new ArrayList<>();
    Produto modelProduto = new Produto();
    ArrayList<String> listaTipos = new ArrayList<>();
    ProdutoController controllerProduto = new ProdutoController();

    /**
     * Creates new form ViewCodigobarras
     */
    public ViewCodigobarras() {
        initComponents();
        setLocationRelativeTo(null);
        carregarprodutos();
    }

    private void carregarprodutos() {
        listaProduto = new ArrayList<>();
        listaProduto = controllerProduto.getListaProdutosController();
        DefaultTableModel modelo = (DefaultTableModel) jtProdutos.getModel();
        int contPagar = listaProduto.size();
        for (int i = 0; i < contPagar; i++) {
            modelo.addRow(new Object[]{
                listaProduto.get(i).getNome(),
                listaProduto.get(i).getCodigoBarrasEan()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCodigos = new javax.swing.JTable();
        jbAdicionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtfExcluir = new javax.swing.JButton();
        jcbTipoCodigo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigoBarras = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNomeProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerador de código de barras");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/blicon.png")).getImage());

        jbgerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-pdf-2-filled-50.png"))); // NOI18N
        jbgerar.setText("Gerar Código");
        jbgerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbgerarActionPerformed(evt);
            }
        });

        jtCodigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome produto", "Código de barras para imprimir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCodigos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtCodigos);

        jbAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-adicionar-filled-50.png"))); // NOI18N
        jbAdicionar.setText("Adicionar código");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite aqui o código de barras:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-fechar-janela-filled-50.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-excluir-filled-50.png"))); // NOI18N
        jtfExcluir.setText("Excluir código da tabela");
        jtfExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfExcluirActionPerformed(evt);
            }
        });

        jcbTipoCodigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EAN13", "EAN8", "UPCA", "UPCE" }));

        jLabel2.setText("Padrão de código de barras");

        jtfCodigoBarras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));
        jtfCodigoBarras.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome produto", "Código de barras"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtProdutos);

        jLabel3.setText("Imprimir");

        jLabel4.setText("Produtos com código de barras cadastrados");

        jLabel5.setText("Nome do produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbgerar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbTipoCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfNomeProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAdicionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdicionar)
                    .addComponent(jtfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbgerar)
                    .addComponent(jButton1)
                    .addComponent(jtfExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbgerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbgerarActionPerformed
//        zerar a lista
        listaProduto = new ArrayList<>();
        //adicionar os itens a lista
        for (int i = 0; i < jtCodigos.getRowCount(); i++) {
            modelProduto = new Produto();
            modelProduto.setNome(jtCodigos.getValueAt(i, 0).toString());
            modelProduto.setCodigoBarrasEan(jtCodigos.getValueAt(i, 1).toString());
            listaProduto.add(modelProduto);
        }
        //gerar o código
        this.gerarCodigoBarras(listaProduto);
    }//GEN-LAST:event_jbgerarActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        //Adiciona linhas na tabela
        if (jcbTipoCodigo.getSelectedItem().toString() == "EAN13" && jtfCodigoBarras.getText().length() != 13) {
            JOptionPane.showMessageDialog(this, "Você deve digitar 13 números para este padrão de código de barras");
        } else {
            if (jcbTipoCodigo.getSelectedItem().toString() == "EAN8" && jtfCodigoBarras.getText().length() != 8) {
                JOptionPane.showMessageDialog(this, "Você deve digitar 8 números para este padrão de código de barras");
            } else {
                DefaultTableModel modelo = (DefaultTableModel) jtCodigos.getModel();
                int cont = 0;
                for (int i = 0; i < cont; i++) {
                    modelo.setNumRows(0);
                }

                //pega a quantidade de linhas e joga na variavel
                modelo.addRow(new Object[]{
                    this.jtfNomeProduto.getText(),
                    this.jtfCodigoBarras.getText()
                });
            }
        }
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void jtfExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfExcluirActionPerformed
        // para excluir a linha
        int linhaSelecionada = jtCodigos.getSelectedRow();
        // Verificamos se existe realmente alguma linha selecionada
        if (linhaSelecionada < 0) {
            return;
        } else {
            // Obtem o modelo da JTable
            DefaultTableModel modelo = (DefaultTableModel) jtCodigos.getModel();
            // Remove a linha
            modelo.removeRow(linhaSelecionada);
        }
    }//GEN-LAST:event_jtfExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jtCodigos.getModel();
        // Remove a linha
        modelo.setNumRows(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProdutosMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = jtProdutos.getSelectedRow();
        // Verificamos se existe realmente alguma linha selecionada
        if (linhaSelecionada < 0) {
            return;
        } else {
            // Obtem o modelo da JTable
            DefaultTableModel modelo = (DefaultTableModel) jtCodigos.getModel();
            //pega a quantidade de linhas e joga na variavel
            modelo.addRow(new Object[]{
                jtProdutos.getValueAt(linhaSelecionada, 0),
                jtProdutos
                        .getValueAt(linhaSelecionada, 1)
            });
        }
    }//GEN-LAST:event_jtProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCodigobarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCodigobarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCodigobarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCodigobarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCodigobarras().setVisible(true);
            }
        });
    }

    public void gerarCodigoBarras(ArrayList<Produto> pListaProduto) {

// criando um objeto da classe Document
        Document document = new Document(PageSize.A4, 50, 50, 50, 50);

        try {

            //Aqui começamos a utilizar as classes do iText: o documento
            //criado acima será
//direcionado para um arquivo PDF.
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("C://BLVendas//relatorios//codigo_barra.pdf"));

//abrindo o documento.
            document.open();

//adicionando um novo paragrafo.
            for (int i = 0; i < pListaProduto.size(); i++) {
                document.add(new Paragraph(pListaProduto.get(i).getNome()));

                document.add(new Paragraph("    "));

                //Comecando a configurar o cod de barras
                PdfContentByte cb = writer.getDirectContent();

                BarcodeEAN codeEAN = new BarcodeEAN();

                //O iText suporta os principais tipos de código de barra, como Barcode39,
//  Barcode128 (128, 128_UCC, 128_RAW),  BarcodeEAN (EAN13, EAN8, UPCA, UPCE), EANSUP, etc
                if (jcbTipoCodigo.getSelectedItem().toString() == "EAN13") {
                    codeEAN.setCodeType(codeEAN.EAN13);
                } else if ("EAN8".equals(jcbTipoCodigo.getSelectedItem().toString())) {
                    codeEAN.setCodeType(codeEAN.EAN8);
                } else if ("UPCA".equals(jcbTipoCodigo.getSelectedItem().toString())) {
                    codeEAN.setCodeType(codeEAN.UPCA);
                } else if ("UPCE".equals(jcbTipoCodigo.getSelectedItem().toString())) {
                    codeEAN.setCodeType(codeEAN.UPCE);
                }

                codeEAN.setCode(pListaProduto.get(i).getCodigoBarrasEan());

                Image imageEAN = codeEAN.createImageWithBarcode(cb, null, null);

                document.add(new Phrase(new Chunk(imageEAN, 0, 0)));
            }
            //abrir o arquivo
            File file = new File("C://BLVendas//relatorios//codigo_barra.pdf");
            try {
                Desktop.getDesktop().open(file);
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();

        } catch (Exception de) {
            JOptionPane.showMessageDialog(this, "Verifique se todos os produtos da tabela tem a quintadade correta\n"
                    + "de numeros do padrão selecionado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            de.printStackTrace();

        }
        document.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbgerar;
    private javax.swing.JComboBox jcbTipoCodigo;
    private javax.swing.JTable jtCodigos;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JFormattedTextField jtfCodigoBarras;
    private javax.swing.JButton jtfExcluir;
    private javax.swing.JTextField jtfNomeProduto;
    // End of variables declaration//GEN-END:variables
}
