/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inosystem.pdv.view;

import com.inosystem.pdv.contoller.CaixaController;
import com.inosystem.pdv.model.Caixa;
import com.inosystem.pdv.model.SessaoUsuario;
import com.inosystem.pdv.util.AtualizadorHorario;
import com.inosystem.pdv.util.Mascara;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author jrpbjr
 */
public class ViewABCaixa extends javax.swing.JFrame {

    CaixaController controllerCaixa = new CaixaController();
    Caixa modelCaixa = new Caixa();
    Mascara bLMascaras = new Mascara();
    private int numeroCaixa;
    ViewPdv viewPdv = new ViewPdv();

    /**
     * Creates new form ViewABCaixa
     */
    public ViewABCaixa() {
        initComponents();
        setLocationRelativeTo(null);
//        new ExecutarSemLogin().autenticar();
        carregarConfiguracoes();
        this.viewPdv = new ViewPdv();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbCaixas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlDataHora = new javax.swing.JLabel();
        jbAbrirFechar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtfDinheiro = new javax.swing.JTextField();
        jtfCartao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfCheque = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfVale = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfValorTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jtfDataAbertura = new com.toedter.calendar.JDateChooser();

        jLabel8.setText("Valor de fechamento:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abertura e Fechamento de caixa");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/blicon.png")).getImage());
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Número do caixa:");

        jcbCaixas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbCaixas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Caixa Nº 01", "Caixa Nº 02", "Caixa Nº 03", "Caixa Nº 04", "Caixa Nº 05", "Caixa Nº 06", "Caixa Nº 07", "Caixa Nº 08", "Caixa Nº 09", "Caixa Nº 10" }));
        jcbCaixas.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbCaixasPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel2.setText("Usuário:");

        jlUsuario.setText("nome do usuario");

        jLabel4.setText("Data/Hora:");

        jlDataHora.setText("data hora");

        jbAbrirFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-caixa-de-seleção-marcada-filled-50.png"))); // NOI18N
        jbAbrirFechar.setText("Abrir/Fechar");
        jbAbrirFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAbrirFecharActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-sair-filled-50.png"))); // NOI18N
        jbCancelar.setText("Sair");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Dados para abertura e fechamento do caixa.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Situação do caixa:");

        jlStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlStatus.setForeground(new java.awt.Color(153, 0, 0));
        jlStatus.setText("status");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Dinheiro");

        jtfDinheiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDinheiroKeyReleased(evt);
            }
        });

        jtfCartao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCartaoKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Cartão:");

        jtfCheque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfCheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfChequeKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Cheque:");

        jtfVale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfVale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfValeKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Convenio:");

        jtfValorTotal.setEditable(false);
        jtfValorTotal.setBackground(new java.awt.Color(204, 204, 204));
        jtfValorTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Valor total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfVale, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jtfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setFocusTraversalPolicyProvider(true);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Data de abertura do caixa:");

        jtfDataAbertura.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAbrirFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbCaixas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlDataHora))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jlStatus))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbCaixas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jlUsuario)
                    .addComponent(jLabel4)
                    .addComponent(jlDataHora))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jlStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAbrirFechar)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAbrirFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAbrirFecharActionPerformed
        // TODO add your handling code here:
        if (jcbCaixas.getSelectedIndex() == 0) {
            //selecione um caixa   
            JOptionPane.showMessageDialog(this, "Você deve selecionar o número do caixa!");
        } else {
            modelCaixa = new Caixa();
            //Abrir ou fechar um caixa
            modelCaixa = controllerCaixa.verificarRetorarCaixaControler(getNumeroCaixa());

            if (modelCaixa.getStatus() == 0) {
                //não tem caixa aberto - abrir caixa
                modelCaixa.setCaixaNumero(getNumeroCaixa());
                modelCaixa.setDinheiro(Double.parseDouble(jtfDinheiro.getText()));
                modelCaixa.setCartao(Double.parseDouble(jtfCartao.getText()));
                modelCaixa.setCheque(Double.parseDouble(jtfCheque.getText()));
                modelCaixa.setConvenio(Double.parseDouble(jtfVale.getText()));
                modelCaixa.setCodigoUsuario(SessaoUsuario.codigo);
                modelCaixa.setStatus(1);
                try {
                    modelCaixa.setDataAbertura(bLMascaras.converterDataParaDateUS(jtfDataAbertura.getDate()));
                } catch (Exception ex) {
                    Logger.getLogger(ViewABCaixa.class.getName()).log(Level.SEVERE, null, ex);
                }
                // salvar novo caixa
                if (modelCaixa.getCodigo() == 0) {
                    if (controllerCaixa.salvarCaixaController(modelCaixa) > 0) {
                        JOptionPane.showMessageDialog(this, "Abertura de caixa realizada com sucesso!", "ATENÇÂO", JOptionPane.WARNING_MESSAGE);
                        viewPdv.setNumeroCaixa(jcbCaixas.getSelectedIndex());
                        viewPdv.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro!", "ERRO", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    //reabrir o caixa
                    if (controllerCaixa.atualizarCaixaController(modelCaixa)) {
                        JOptionPane.showMessageDialog(this, "Abertura de caixa realizada com sucesso!", "ATENÇÂO", JOptionPane.WARNING_MESSAGE);
                        viewPdv.setNumeroCaixa(jcbCaixas.getSelectedIndex());
                        viewPdv.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro!", "ERRO", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                //tem caixa aberto - fechar caixa
                Object opcoes[] = {"Ir para PDV", "Fechar Caixa", "Cancelar"};
                int op = JOptionPane.showOptionDialog(null, "Você deseja fechar o caixa ou ir para o PDV", "O caixa está aberto", 1, 3, null, opcoes, null);
                switch (op) {
                    case 1:
                        //quero fechar o caixa
                        modelCaixa.setStatus(0);
                        try {
                            modelCaixa.setDataAbertura(bLMascaras.converterDataParaDateUS(jtfDataAbertura.getDate()));
                            modelCaixa.setDataFechamento(bLMascaras.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
                        } catch (Exception ex) {
                            Logger.getLogger(ViewABCaixa.class.getName()).log(Level.SEVERE, null, ex);
                        }   // salvar novo caixa   // salvar novo caixa
                        if (controllerCaixa.atualizarCaixaController(modelCaixa)) {
                            JOptionPane.showMessageDialog(this, "Fechamento de caixa realizado com sucesso!", "ATENÇÂO", JOptionPane.WARNING_MESSAGE);
                            carregarCaixa();
                            limparTela();
                        } else {
                            JOptionPane.showMessageDialog(this, "Erro!", "ERRO", JOptionPane.ERROR_MESSAGE);
                        }
                        break;
                    case 0:
                        //quero continuar com caixa aberto
                        //setar o numero do caixa e fechar
                        viewPdv.setNumeroCaixa(jcbCaixas.getSelectedIndex());
                        viewPdv.setNumeroCaixaLabel(jcbCaixas.getSelectedIndex());
                        viewPdv.setVisible(true);
                        dispose();
                        break;
                    case 2:
                        dispose();
                        break;
                    default:
                        break;
                }
            }
        }
    }//GEN-LAST:event_jbAbrirFecharActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jcbCaixasPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbCaixasPopupMenuWillBecomeInvisible
        carregarCaixa();
    }//GEN-LAST:event_jcbCaixasPopupMenuWillBecomeInvisible

    private void jtfDinheiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDinheiroKeyReleased
        // TODO add your handling code here:
        this.jtfDinheiro.setText(new Mascara().converterVirgulaParaPonto(this.jtfDinheiro.getText()));
        somarValorTotal();
    }//GEN-LAST:event_jtfDinheiroKeyReleased

    private void jtfCartaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCartaoKeyReleased
        // TODO add your handling code here:
        this.jtfCartao.setText(new Mascara().converterVirgulaParaPonto(this.jtfCartao.getText()));
        somarValorTotal();
    }//GEN-LAST:event_jtfCartaoKeyReleased

    private void jtfChequeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfChequeKeyReleased
        // TODO add your handling code here:
        this.jtfCheque.setText(new Mascara().converterVirgulaParaPonto(this.jtfCheque.getText()));
        somarValorTotal();
    }//GEN-LAST:event_jtfChequeKeyReleased

    private void jtfValeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValeKeyReleased
        // TODO add your handling code here:
        this.jtfVale.setText(new Mascara().converterVirgulaParaPonto(this.jtfVale.getText()));
        somarValorTotal();
    }//GEN-LAST:event_jtfValeKeyReleased

    private void limparTela() {
        jtfDinheiro.setText("0");
        jtfCartao.setText("0");
        jtfCheque.setText("0");
        jtfVale.setText("0");
        jtfValorTotal.setText("0");

    }

    private void carregarCaixa() {
        // TODO add your handling code here:
        modelCaixa = new Caixa();
        setNumeroCaixa(jcbCaixas.getSelectedIndex());
        //verifica se o caixa ta aberto se tiver retorna os dados
        modelCaixa = controllerCaixa.verificarRetorarCaixaControler(getNumeroCaixa());
        if (modelCaixa.getStatus() == 0) {
            // não tem caixa aberto
            //cadastrar novo caixa
            try {
                jtfDataAbertura.setDate(bLMascaras.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
            } catch (Exception ex) {
                Logger.getLogger(ViewABCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
            jtfDinheiro.setText("0");
            jtfCartao.setText("0");
            jtfCheque.setText("0");
            jtfVale.setText("0");
            habilitarCampos(true);
            jlStatus.setText("Caixa fechado");
            jbAbrirFechar.setText("Abrir caixa");

        } else {
            //tem caixa aberto
            //alterar caixa
            habilitarCampos(false);
            jtfDataAbertura.setDate(modelCaixa.getDataAbertura());
            jtfDinheiro.setText(bLMascaras.arredondamentoDoubleComPontoDuasCasasString(modelCaixa.getDinheiro()));
            jtfCartao.setText(bLMascaras.arredondamentoDoubleComPontoDuasCasasString(modelCaixa.getCartao()));
            jtfCheque.setText(bLMascaras.arredondamentoDoubleComPontoDuasCasasString(modelCaixa.getCheque()));
            jtfVale.setText(bLMascaras.arredondamentoDoubleComPontoDuasCasasString(modelCaixa.getConvenio()));
            somarValorTotal();
            jlStatus.setText("Caixa aberto");
            jbAbrirFechar.setText("Fechar ou PDV");
        }
    }

    private void somarValorTotal() {
        double dinheiro = 0, cartao = 0, cheque = 0, convenio = 0;
        try {
            dinheiro = Double.parseDouble(jtfDinheiro.getText());
        } catch (Exception e) {
            dinheiro = 0;
        }
        try {
            cartao = Double.parseDouble(jtfCartao.getText());
        } catch (Exception e) {
            cartao = 0;
        }
        try {
            cheque = Double.parseDouble(jtfCheque.getText());
        } catch (Exception e) {
            cheque = 0;
        }
        try {
            convenio = Double.parseDouble(jtfVale.getText());
        } catch (Exception e) {
            convenio = 0;
        }
        jtfValorTotal.setText(bLMascaras.arredondamentoDoubleComPontoDuasCasasString(dinheiro + cartao + cheque + convenio));

    }

    private void habilitarCampos(boolean status) {
        jtfDinheiro.setEnabled(status);
        jtfCartao.setEnabled(status);
        jtfCheque.setEnabled(status);
        jtfVale.setEnabled(status);
    }

    private void carregarConfiguracoes() {
        jlUsuario.setText(SessaoUsuario.nome);
        AtualizadorHorario ah = new AtualizadorHorario(jlDataHora);
        ah.mostrarData(true);
        Thread thHora = ah;
        thHora.start();
        setNumeroCaixa(jcbCaixas.getSelectedIndex());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewABCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewABCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewABCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewABCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewABCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbAbrirFechar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jcbCaixas;
    private javax.swing.JLabel jlDataHora;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JTextField jtfCartao;
    private javax.swing.JTextField jtfCheque;
    private com.toedter.calendar.JDateChooser jtfDataAbertura;
    private javax.swing.JTextField jtfDinheiro;
    private javax.swing.JTextField jtfVale;
    private javax.swing.JTextField jtfValorTotal;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the numeroCaixa
     */
    public int getNumeroCaixa() {
        return numeroCaixa;
    }

    /**
     * @param numeroCaixa the numeroCaixa to set
     */
    public void setNumeroCaixa(int numeroCaixa) {
        this.numeroCaixa = numeroCaixa;
    }
}
