/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inosystem.pdv.nfe.view;

import com.inosystem.pdv.nfe.model.XmlNfe;
import com.inosystem.pdv.nfe.util.LerArqXML;
import com.inosystem.pdv.nfe.util.TraduzirXmlNfe;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jdom2.Attribute;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;

/**
 *
 * @author jrpbjr
 */
public class ViewLeitorNotaXML extends javax.swing.JFrame {

    String caminho_escolha;
    String fileName = "", nomeArqXml = "";
    XmlNfe modelXmlNfe = new XmlNfe();
    TraduzirXmlNfe traduzirXmlNfe = new TraduzirXmlNfe();

    /**
     * Creates new form ViewLeitorNotaXML
     */
    public ViewLeitorNotaXML() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public String escolheArq() {
        String arquivo = null;
        File[] arquivos = escolhe_arquivo(true, caminho_escolha, JFileChooser.FILES_ONLY, "xml");
        if (arquivos != null) {
            for (int i = 0; i < arquivos.length; i++) {
                arquivo = arquivos[i].getAbsolutePath();
                nomeArqXml = arquivos[i].getName();
            }
        }
        return arquivo;
    }

    public File[] escolhe_arquivo(boolean multiplo, String caminho, int tipo_arq, String ext_arq) {
        SwingUtilities.updateComponentTreeUI(getContentPane());
        JFileChooser fc_escolha = new JFileChooser(caminho);
        fc_escolha.setDialogTitle("Escolha o Arquivo para Leitura");
        fc_escolha.setApproveButtonText("Confirma");
        fc_escolha.setFileSelectionMode(tipo_arq);
        //fc_escolha.setDialogType(JFileChooser.CUSTOM_DIALOG);
        if (ext_arq != null) {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos " + ext_arq, ext_arq.toLowerCase(), ext_arq.toUpperCase());
            fc_escolha.setFileFilter(filter);
        }
        fc_escolha.setBounds(10, 30, 300, 350);
        fc_escolha.setAutoscrolls(true);
        fc_escolha.setMultiSelectionEnabled(multiplo);
        int returnVal = fc_escolha.showOpenDialog(getContentPane());
        SwingUtilities.updateComponentTreeUI(getContentPane());
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File[] f_result = fc_escolha.getSelectedFiles();
            //System.out.println("Saiu de Filechooser com OPEN");
            return f_result;
        } else {
            //System.out.println("Saiu de Filechooser com CANCEL");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfNfe = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizador de NFe em XML");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/blicon.png")).getImage());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-binóculos-filled-50.png"))); // NOI18N
        jButton1.setText("Localizarr nota fiscal XML");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfNfe.setColumns(20);
        jtfNfe.setRows(5);
        jScrollPane1.setViewportView(jtfNfe);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-sair-filled-50.png"))); // NOI18N
        jButton2.setText("Sair do vizualizador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lerarq(escolheArq());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lerarq(String pCaminho) {
        //Aqui você informa o nome do arquivo XML.  
        File f = new File(pCaminho);

        //Criamos uma classe SAXBuilder que vai processar o XML  
        SAXBuilder sb = new SAXBuilder();

        //Este documento agora possui toda a estrutura do arquivo.  
        Document d;
        try {
            d = sb.build(f);
            //Recuperamos o elemento root  
            Element nfe = d.getRootElement();

            //Recuperamos os elementos filhos (children)  
            List elements = nfe.getChildren();
            Iterator i = elements.iterator();

            //Iteramos com os elementos filhos, e filhos do dos filhos  
            while (i.hasNext()) {
                Element element = (Element) i.next();
                trataElement(element);
            }

        } catch (JDOMException ex) {
            Logger.getLogger(LerArqXML.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LerArqXML.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void trataElement(Element element) {

        //Recuperamos os atributos filhos (Attributes)  
        List atributes = element.getAttributes();
        Iterator i_atr = atributes.iterator();

        //Iteramos com os atributos filhos  
        while (i_atr.hasNext()) {
            Attribute atrib = (Attribute) i_atr.next();
            jtfNfe.setText(jtfNfe.getText() + "\n" + "\n" + traduzirXmlNfe.traduzir(atrib.getName()) + ": " + atrib.getValue());
        }
        //Recuperamos os elementos filhos (children)  
        List elements = element.getChildren();
        Iterator it = elements.iterator();

        //Iteramos com os elementos filhos, e filhos do dos filhos  
        while (it.hasNext()) {
            Element el = (Element) it.next();
            jtfNfe.setText(jtfNfe.getText() + "\n" + traduzirXmlNfe.traduzir(el.getName()) + ": " + el.getText());
            trataElement(el);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLeitorNotaXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLeitorNotaXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLeitorNotaXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLeitorNotaXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLeitorNotaXML().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtfNfe;
    // End of variables declaration//GEN-END:variables
}
