/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inosystem.pdv.nfe.view;

import com.inosystem.pdv.contoller.EmpresaController;
import com.inosystem.pdv.model.Empresa;
import com.inosystem.pdv.util.ExecutarSemLogin;
import nfe.controller.ControllerAssinaturaDigital;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelAssinaturaDigital;

/**
 *
 * @author jrpbjr
 */
public class ViewParAssDigital extends javax.swing.JFrame {

    EmpresaController controllerEmpresa = new EmpresaController();
    Empresa modelEmpresa = new Empresa();
    ArrayList<Empresa> listaEmpresas = new ArrayList<>();
    ControllerAssinaturaDigital controllerAssinaturaDigital = new ControllerAssinaturaDigital();
    ModelAssinaturaDigital modelAssinaturaDigital = new ModelAssinaturaDigital();
    ArrayList<ModelAssinaturaDigital> listaModelAssinaturaDigitals = new ArrayList<>();
    String tipoCadastro;

    /**
     * Creates new form ViewParAssDigital
     */
    public ViewParAssDigital() {
        initComponents();
        new ExecutarSemLogin().autenticar();
        listarEmpresas();
        carregarAssinaturas();
        tipoCadastro = "novo";
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbCodigoEmpresa = new javax.swing.JComboBox<>();
        jcbNomeEmpresa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfSenhaKeystore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfSerie55 = new javax.swing.JTextField();
        jtfSerie65 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfVersao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfIDToken = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfCSCHomologacao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfCSCProducao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAssinaturas = new javax.swing.JTable();
        jbLimpar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jtfSenhaTruststore = new javax.swing.JPasswordField();
        jtfSenhaToken = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parametro Assinatura Digital");
        setResizable(false);

        jtfCodigo.setEditable(false);

        jLabel1.setText("Código");

        jcbCodigoEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCodigoEmpresa.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbCodigoEmpresaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jcbNomeEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbNomeEmpresa.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbNomeEmpresaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel2.setText("Empresa");

        jLabel3.setText("Senha truststore");

        jLabel4.setText("Senha token");

        jLabel5.setText("Senha keystore");

        jLabel6.setText("Serie 55");

        jLabel7.setText("Serie 65");

        jLabel8.setText("Versão");

        jLabel9.setText("ID Token");

        jLabel10.setText("Csc Homologação");

        jLabel11.setText("Csc Produção");

        jtAssinaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Empresa", "Versão", "ID Token"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtAssinaturas);
        if (jtAssinaturas.getColumnModel().getColumnCount() > 0) {
            jtAssinaturas.getColumnModel().getColumn(0).setMinWidth(50);
            jtAssinaturas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtAssinaturas.getColumnModel().getColumn(0).setMaxWidth(50);
            jtAssinaturas.getColumnModel().getColumn(3).setMinWidth(80);
            jtAssinaturas.getColumnModel().getColumn(3).setPreferredWidth(80);
            jtAssinaturas.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-fechar-janela-filled-50.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-excluir-filled-50.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-ponta-do-lápis-filled-50.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-salvar-filled-50.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbCodigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbNomeEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jtfSenhaTruststore, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jtfSenhaToken, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jtfSenhaKeystore, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfSerie55, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfSerie65, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jtfVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jtfIDToken, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jtfCSCHomologacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jtfCSCProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSenhaKeystore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCodigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfSenhaTruststore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSenhaToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfSerie55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfSerie65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIDToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCSCHomologacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCSCProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar)
                    .addComponent(jbExcluir)
                    .addComponent(jbAlterar)
                    .addComponent(jbSalvar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        if (tipoCadastro.equals("novo")) {
            salvar();
        } else if (tipoCadastro.equals("alteracao")) {
            alterar();
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int linhaSelecionada = jtAssinaturas.getSelectedRow();
        // Verificamos se existe realmente alguma linha selecionada
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um item na tabela antes de clicar no botão!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        } else {
            this.excluir();
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        int linhaSelecionada = jtAssinaturas.getSelectedRow();
        // Verificamos se existe realmente alguma linha selecionada
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um item na tabela antes de clicar no botão!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        } else {
            tipoCadastro = "alteracao";
            retornar();
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jcbNomeEmpresaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbNomeEmpresaPopupMenuWillBecomeInvisible
        if (this.jcbNomeEmpresa.isPopupVisible()) {
            modelEmpresa = controllerEmpresa.getEmpresaController(jcbNomeEmpresa.getSelectedItem().toString()).getEmpresa();
            jcbCodigoEmpresa.setSelectedItem(modelEmpresa.getCodigo());
        }
    }//GEN-LAST:event_jcbNomeEmpresaPopupMenuWillBecomeInvisible

    private void jcbCodigoEmpresaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbCodigoEmpresaPopupMenuWillBecomeInvisible
        if (this.jcbCodigoEmpresa.isPopupVisible()) {
            modelEmpresa = controllerEmpresa.getEmpresaController(Integer.parseInt(jcbCodigoEmpresa.getSelectedItem().toString())).getEmpresa();
            jcbNomeEmpresa.setSelectedItem(modelEmpresa.getRazaoSocial());
        }
    }//GEN-LAST:event_jcbCodigoEmpresaPopupMenuWillBecomeInvisible

    //excluir um banco selecionado
    private void excluir() {
        int linha = jtAssinaturas.getSelectedRow();
        String nome = (String) jtAssinaturas.getValueAt(linha, 2);
        int codigo = (Integer) jtAssinaturas.getValueAt(linha, 0);
        //pegunta se realmente deseja excluir
        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja"
                + " excluir o registro \nNome: "
                + nome + " ?", "Atenção", JOptionPane.YES_NO_OPTION);
        //se sim exclui, se não não faz nada    
        if (opcao == JOptionPane.OK_OPTION) {
            if (controllerAssinaturaDigital.excluirAssinaturaDigitalController(codigo)) {
                JOptionPane.showMessageDialog(this, "Registro excluido com suscesso!");
                carregarAssinaturas();
            } else {
                JOptionPane.showMessageDialog(this, "Você não pode excluir uma que possui vinculos!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    //salvar alterações
    private boolean alterar() {
        modelAssinaturaDigital = new ModelAssinaturaDigital();
        modelAssinaturaDigital.setCodigo(Integer.parseInt(jtfCodigo.getText()));
        modelAssinaturaDigital.setEmpresa(Integer.parseInt(jcbCodigoEmpresa.getSelectedItem().toString()));
        modelAssinaturaDigital.setSenhaTruststore(jtfSenhaTruststore.getText());
        modelAssinaturaDigital.setSenhaToken(jtfSenhaToken.getText());
        modelAssinaturaDigital.setSenhaKeystore(jtfSenhaKeystore.getText());
        modelAssinaturaDigital.setSerie55(jtfSerie55.getText());
        modelAssinaturaDigital.setSerie65(jtfSerie65.getText());
        modelAssinaturaDigital.setVerproc(jtfVersao.getText());
        modelAssinaturaDigital.setIdtoken(jtfIDToken.getText());
        modelAssinaturaDigital.setCsc(jtfCSCHomologacao.getText());
        modelAssinaturaDigital.setCscProd(jtfCSCProducao.getText());

        //alterar 
        if (controllerAssinaturaDigital.atualizarAssinaturaDigitalController(modelAssinaturaDigital)) {
            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
            this.limparCampos();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    //salvar novo banco
    private boolean salvar() {
        modelAssinaturaDigital = new ModelAssinaturaDigital();
        modelAssinaturaDigital.setEmpresa(Integer.parseInt(jcbCodigoEmpresa.getSelectedItem().toString()));
        modelAssinaturaDigital.setSenhaTruststore(new String(jtfSenhaTruststore.getPassword()));
        modelAssinaturaDigital.setSenhaToken(new String(jtfSenhaToken.getPassword()));
        modelAssinaturaDigital.setSenhaKeystore(jtfSenhaKeystore.getText());
        modelAssinaturaDigital.setSerie55(jtfSerie55.getText());
        modelAssinaturaDigital.setSerie65(jtfSerie65.getText());
        modelAssinaturaDigital.setVerproc(jtfVersao.getText());
        modelAssinaturaDigital.setIdtoken(jtfIDToken.getText());
        modelAssinaturaDigital.setCsc(jtfCSCHomologacao.getText());
        modelAssinaturaDigital.setCscProd(jtfCSCProducao.getText());
        //salvar 
        if (controllerAssinaturaDigital.salvarAssinaturaDigitalController(modelAssinaturaDigital) > 0) {
            JOptionPane.showMessageDialog(this, "Registro gravado com sucesso!");
            this.limparCampos();
            this.carregarAssinaturas();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao gravar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean retornar() {
        //recebe a linha selecionada
        int linha = this.jtAssinaturas.getSelectedRow();
        //pega o codigo do cliente na linha selecionada
        int codigo = (Integer) jtAssinaturas.getValueAt(linha, 0);

        try {
            //recupera os dados do banco
            modelAssinaturaDigital = controllerAssinaturaDigital.getAssinaturaDigitalController(codigo);
            //seta os dados na interface
            this.jtfCodigo.setText(String.valueOf(modelAssinaturaDigital.getCodigo()));
            this.jcbCodigoEmpresa.setSelectedItem(modelAssinaturaDigital.getEmpresa());
            this.jtfSenhaTruststore.setText(modelAssinaturaDigital.getSenhaTruststore());
            this.jtfSenhaToken.setText(modelAssinaturaDigital.getSenhaToken());
            this.jtfSenhaKeystore.setText(modelAssinaturaDigital.getSenhaKeystore());
            this.jtfSerie55.setText(modelAssinaturaDigital.getSerie55());
            this.jtfSerie65.setText(modelAssinaturaDigital.getSerie65());
            this.jtfVersao.setText(modelAssinaturaDigital.getVerproc());
            this.jtfIDToken.setText(modelAssinaturaDigital.getIdtoken());
            this.jtfCSCHomologacao.setText(modelAssinaturaDigital.getCsc());
            this.jtfCSCProducao.setText(modelAssinaturaDigital.getCscProd());

            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    private void limparCampos() {
        jtfCodigo.setText("");
        jtfSenhaTruststore.setText("");
        jtfSenhaToken.setText("");
        jtfSenhaKeystore.setText("");
        jtfSerie55.setText("");
        jtfSerie65.setText("");
        jtfVersao.setText("");
        jtfIDToken.setText("");
        jtfCSCHomologacao.setText("");
        jtfCSCProducao.setText("");
        carregarAssinaturas();
        listarEmpresas();
        tipoCadastro = "novo";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewParAssDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewParAssDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewParAssDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewParAssDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewParAssDigital().setVisible(true);
            }
        });
    }

    // carregar assinaturas salvos
    private void carregarAssinaturas() {
        listaModelAssinaturaDigitals = controllerAssinaturaDigital.getListaAssinaturaDigitalController();
        DefaultTableModel modelo = (DefaultTableModel) jtAssinaturas.getModel();
        modelo.setNumRows(0);
        String assinatura = "";
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listaModelAssinaturaDigitals.size();
        for (int i = 0; i < cont; i++) {
            assinatura = controllerEmpresa.getEmpresaController(listaModelAssinaturaDigitals.get(i).getEmpresa()).getEmpresa().getRazaoSocial();
            modelo.addRow(new Object[]{
                listaModelAssinaturaDigitals.get(i).getCodigo(),
                assinatura,
                listaModelAssinaturaDigitals.get(i).getVerproc(),
                listaModelAssinaturaDigitals.get(i).getIdtoken()
            });
        }
    }

    private void listarEmpresas() {
        try {
            listaEmpresas = controllerEmpresa.getListaEmpresaController();
        } catch (Exception ex) {
            Logger.getLogger(ViewParAssDigital.class.getName()).log(Level.SEVERE, null, ex);
        }
        jcbCodigoEmpresa.removeAllItems();
        jcbNomeEmpresa.removeAllItems();
        for (int i = 0; i < listaEmpresas.size(); i++) {
            jcbCodigoEmpresa.addItem(listaEmpresas.get(i).getCodigo() + "");
            jcbNomeEmpresa.addItem(listaEmpresas.get(i).getRazaoSocial());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbCodigoEmpresa;
    private javax.swing.JComboBox<String> jcbNomeEmpresa;
    private javax.swing.JTable jtAssinaturas;
    private javax.swing.JTextField jtfCSCHomologacao;
    private javax.swing.JTextField jtfCSCProducao;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfIDToken;
    private javax.swing.JTextField jtfSenhaKeystore;
    private javax.swing.JPasswordField jtfSenhaToken;
    private javax.swing.JPasswordField jtfSenhaTruststore;
    private javax.swing.JTextField jtfSerie55;
    private javax.swing.JTextField jtfSerie65;
    private javax.swing.JTextField jtfVersao;
    // End of variables declaration//GEN-END:variables
}
