/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inosystem.pdv.nfe.view;


import com.inosystem.pdv.contoller.ClienteController;
import com.inosystem.pdv.contoller.EmpresaController;
import com.inosystem.pdv.contoller.ProdutoController;
import com.inosystem.pdv.model.Banco;
import com.inosystem.pdv.model.Cliente;
import com.inosystem.pdv.model.Empresa;
import com.inosystem.pdv.model.FormaPagamento;
import com.inosystem.pdv.model.Produto;
import com.inosystem.pdv.model.Transportadora;
import com.inosystem.pdv.model.Venda;
import com.inosystem.pdv.nfe.model.Inf;
import com.inosystem.pdv.util.ExecutarSemLogin;
import com.inosystem.pdv.util.Mascara;
import com.inosystem.pdv.view.ViewVerificarPermissao;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import nfe.controller.ControllerNF;
import nfe.model.Inf;

/**
 *
 * @author jrpbjr
 */
public class ViewNFe extends javax.swing.JFrame {

    Produto modelProdutos = new Produto();
    ArrayList<Produto> listaProduto = new ArrayList<>();
    ArrayList<Cliente> listaClientes = new ArrayList<>();
    ClienteController controllerCliente = new ClienteController();
    Cliente modelCliente = new Cliente();
    ProdutoController controllerProdutos = new ProdutoController();
    FormaPagamentoController controllerTipoPagamento = new FormaPagamentoController();
    ArrayList<FormaPagamento> listaModelTipoPagamentos = new ArrayList<>();
    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    Venda modelVendas = new Venda();
    VendaController VendaController = new VendaController();
    VendaControllerProdutos VendaControllerProdutos = new VendaControllerProdutos();
    ArrayList<VendaProdutos> listaVendaProdutoses = new ArrayList<>();
    ArrayList<Venda> listaVendaes = new ArrayList<>();
    private ViewVerificarPermissao viewVerificarPermissao;
    FormaPagamentoController controllerFormaPagamento = new FormaPagamentoController();
    FormaPagamento modelFormaPagamento = new FormaPagamento();
    ArrayList<FormaPagamento> listaFormaPagamentos = new ArrayList<>();
    Mascara bLMascaras = new Mascara();
    int contVendaMenor;
    ControllerUnidadeMedia controllerUnidadeMedia = new ControllerUnidadeMedia();
    ControllerTransportadora controllerTransportadora = new ControllerTransportadora();
    ArrayList<Transportadora> listaTransportadoras = new ArrayList<>();
    ArrayList<Venda> listaVendaAlterar = new ArrayList<>();
    ControllerBanco controllerBanco = new ControllerBanco();
    Banco modelBanco = new Banco();
    ArrayList<Banco> listaBancos = new ArrayList<>();
    ControllerNF controllerNF = new ControllerNF();
    Inf modelNF = new Inf();
    ArrayList<Inf> listaInfs = new ArrayList<>();
    EmpresaController controllerEmpresa = new EmpresaController();
    Empresa modelEmpresa = new Empresa();

    /**
     * Creates new form ViewNFe
     */
    public ViewNFe() {
        initComponents();
        setLocationRelativeTo(null);
        new ExecutarSemLogin().autenticar();
        this.viewVerificarPermissao = new ViewVerificarPermissao(this, true);
        listarCodigoVendas();
        listarFormaPagamento();
        listarClientes();
        carregarTransportadora();
        listarBancos();
        preencherFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jtfIPIVlr = new javax.swing.JTextField();
        jtfValorTotalprodutos = new javax.swing.JTextField();
        jdCancelamento = new com.toedter.calendar.JDateChooser();
        jtfSerie = new javax.swing.JTextField();
        jtfPisBC = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jtfICMSBC = new javax.swing.JTextField();
        jtfEmpresa = new javax.swing.JTextField();
        jcbTipoNFe = new javax.swing.JComboBox<>();
        jcbBanco = new javax.swing.JComboBox<>();
        jtfCofinsBC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfNPedido = new javax.swing.JTextField();
        jcbCodigoTransportadora = new javax.swing.JComboBox<>();
        jtfNNFeNFCe = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jtfPISVlr = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtfQtVolumes = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jtfCofinsVlr = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcbCodigoCliente = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdEmissao = new com.toedter.calendar.JDateChooser();
        jtfDescontoProdutos = new javax.swing.JTextField();
        jtfDadosAdicionais = new javax.swing.JTextField();
        jtfChaveNFeR = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jtfPesoVolumes = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfValorBrutoProdutos = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jtfICMSVlr = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jtfNumeroNFEFat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jcbTransportadora = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbFormaPagamento = new javax.swing.JComboBox<>();
        jtfChave = new javax.swing.JTextField();
        jtfPlaca = new javax.swing.JTextField();
        jtfIPIBC = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jdDigitacao = new com.toedter.calendar.JDateChooser();
        jtfMod = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        jbCancelar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jtfUFPlaca = new javax.swing.JComboBox<>();
        jbGerarXML = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtNfe = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jtfTextoPesquisar = new javax.swing.JTextField();
        jcbFiltro = new javax.swing.JComboBox<>();
        jbPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Emissão de Nota Fiscal");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Homologação");
        jPanel1.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Situação: ");
        jPanel1.add(jLabel1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modo: ");
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Off-line");
        jPanel1.add(jLabel4);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jtfIPIVlr, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 110, -1));
        jPanel4.add(jtfValorTotalprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 95, -1));
        jPanel4.add(jdCancelamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 140, -1));
        jPanel4.add(jtfSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 50, -1));
        jPanel4.add(jtfPisBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 110, -1));

        jLabel37.setText("ICMS Vlr");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));
        jPanel4.add(jtfICMSBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 110, -1));

        jtfEmpresa.setEditable(false);
        jPanel4.add(jtfEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 630, -1));

        jcbTipoNFe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Complementar", "Ajuste", "Devolução" }));
        jPanel4.add(jcbTipoNFe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 147, -1));

        jPanel4.add(jcbBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 184, -1));
        jPanel4.add(jtfCofinsBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 110, -1));

        jLabel10.setText("Nome cliente");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));
        jPanel4.add(jtfNPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 161, -1));

        jPanel4.add(jcbCodigoTransportadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 75, -1));
        jPanel4.add(jtfNNFeNFCe, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 95, -1));

        jLabel22.setText("Qt. volumes");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jLabel40.setText("Cofins Vlr");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 80, -1));

        jLabel9.setText("Código cliente");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel23.setText("Num. da NFe e Fat.");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 110, -1));

        jLabel38.setText("PIS Vlr");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 112, -1));
        jPanel4.add(jtfPISVlr, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 110, -1));

        jLabel25.setText("Dta Cancelamento");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jLabel16.setText("Dados adicionais");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));
        jPanel4.add(jtfQtVolumes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 95, -1));

        jLabel33.setText("IPI BC");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 50, -1));
        jPanel4.add(jtfCofinsVlr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 100, -1));

        jLabel14.setText("UF placa");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel15.setText("Pedido cliente");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        jcbCodigoCliente.setEnabled(false);
        jcbCodigoCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbCodigoClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel4.add(jcbCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 95, -1));

        jLabel21.setText("Vlr total produtos");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, -1, -1));

        jLabel32.setText("Chave NFe referenciada");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel35.setText("PIS BC");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jLabel11.setText("Forma de pagamento");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));
        jPanel4.add(jdEmissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 140, -1));
        jPanel4.add(jtfDescontoProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 95, -1));
        jPanel4.add(jtfDadosAdicionais, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 270, -1));
        jPanel4.add(jtfChaveNFeR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 210, -1));

        jLabel26.setText("Serie");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, -1, -1));
        jPanel4.add(jtfPesoVolumes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 95, -1));

        jLabel30.setText("Peso dos volumes");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel5.setText("Nº do pedido/venda");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel4.add(jtfValorBrutoProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 95, -1));

        jLabel39.setText("Cofins BC");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, -1));
        jPanel4.add(jtfICMSVlr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 110, -1));

        jLabel36.setText("ICMS BC");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel29.setText("Chave");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel4.add(jtfNumeroNFEFat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 110, -1));

        jLabel12.setText("Transportadora");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel27.setText("Mod");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, -1, -1));

        jLabel18.setText("Vlr dos produtos");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 95, -1));

        jLabel17.setText("Num. NFe/NFCe");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        jLabel28.setText("Emissão");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, -1, -1));

        jPanel4.add(jcbTransportadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 232, -1));

        jLabel8.setText("Empresa:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel13.setText("Placa veículo");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jPanel4.add(jcbFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 171, -1));
        jPanel4.add(jtfChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, -1));
        jPanel4.add(jtfPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 90, -1));
        jPanel4.add(jtfIPIBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 110, -1));

        jLabel34.setText("IPI Vlr");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jLabel24.setText("Data digitação");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));
        jPanel4.add(jdDigitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 140, -1));
        jPanel4.add(jtfMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 50, -1));

        jLabel19.setText("Tipo NFe");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel20.setText("Descontos");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, -1, -1));

        jLabel6.setText("Banco");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade", "Valor Unitário", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbProdutos);
        if (tbProdutos.getColumnModel().getColumnCount() > 0) {
            tbProdutos.getColumnModel().getColumn(0).setMinWidth(100);
            tbProdutos.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbProdutos.getColumnModel().getColumn(0).setMaxWidth(100);
            tbProdutos.getColumnModel().getColumn(2).setMinWidth(100);
            tbProdutos.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbProdutos.getColumnModel().getColumn(2).setMaxWidth(100);
            tbProdutos.getColumnModel().getColumn(3).setMinWidth(100);
            tbProdutos.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbProdutos.getColumnModel().getColumn(3).setMaxWidth(100);
            tbProdutos.getColumnModel().getColumn(4).setMinWidth(100);
            tbProdutos.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbProdutos.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 940, 150));

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-fechar-janela-filled-50.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-arquivo-filled-50.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jPanel4.add(jbLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-salvar-filled-50.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        jPanel4.add(jbSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, -1, -1));

        jtfUFPlaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));
        jPanel4.add(jtfUFPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 70, -1));

        jbGerarXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-caixa-de-seleção-marcada-filled-50.png"))); // NOI18N
        jbGerarXML.setText("Gerar XML");
        jbGerarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGerarXMLActionPerformed(evt);
            }
        });
        jPanel4.add(jbGerarXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, -1, -1));

        jTabbedPane1.addTab("Emissão", jPanel4);

        jtNfe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nº NFe", "Data", "Cliente", "Transportadora", "Qtd. Volumes", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtNfe);
        if (jtNfe.getColumnModel().getColumnCount() > 0) {
            jtNfe.getColumnModel().getColumn(0).setMinWidth(70);
            jtNfe.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtNfe.getColumnModel().getColumn(0).setMaxWidth(70);
            jtNfe.getColumnModel().getColumn(1).setMinWidth(100);
            jtNfe.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtNfe.getColumnModel().getColumn(1).setMaxWidth(100);
            jtNfe.getColumnModel().getColumn(4).setMinWidth(70);
            jtNfe.getColumnModel().getColumn(4).setPreferredWidth(70);
            jtNfe.getColumnModel().getColumn(4).setMaxWidth(70);
            jtNfe.getColumnModel().getColumn(5).setMinWidth(70);
            jtNfe.getColumnModel().getColumn(5).setPreferredWidth(70);
            jtNfe.getColumnModel().getColumn(5).setMaxWidth(70);
        }

        jLabel31.setText("Pesquisar NFe:");

        jcbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbPesquisar.setText("Pesquisar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfTextoPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTextoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbNPedidoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbNPedidoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (this.jcbNPedido.isPopupVisible()) {
            preencherFormulario();
        }
    }//GEN-LAST:event_jcbNPedidoPopupMenuWillBecomeInvisible

    private void jcbCodigoClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbCodigoClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (this.jcbCodigoCliente.isPopupVisible()) {
            this.retornarClientePeloCodigo(Integer.parseInt(jcbCodigoCliente.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_jcbCodigoClientePopupMenuWillBecomeInvisible

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // Salvar nfe 34 campos no formulário e 46 aqui
        modelNF = new Inf();
        modelNF.setChaveNfe(jtfChaveNFeR.getText());
        modelNF.setCodBanco(controllerBanco.getBancoController(jcbBanco.getSelectedItem().toString()).getCodigo());
        modelNF.setCodCliente(Integer.parseInt(jcbCodigoCliente.getSelectedItem().toString()));
        modelNF.setCodFormaPgto(controllerFormaPagamento.getFormaPagamentoController(jcbFormaPagamento.getSelectedItem().toString()).getCodigo());
        //verificar cod tipo doc
        modelNF.setCodTipoDoc("1");
        modelNF.setCodTransportadora(Integer.parseInt(jcbCodigoTransportadora.getSelectedItem().toString()));
        modelNF.setCofinsBc(Double.parseDouble(jtfCofinsBC.getText()));
        modelNF.setCofinsVlr(Double.parseDouble(jtfCofinsVlr.getText()));
        modelNF.setDadosAdicionais(jtfDadosAdicionais.getText());
        //verificar data de devolução
        modelNF.setDataDevolucao(null);
        try {
            modelNF.setDataDigitacao(bLMascaras.converterDataParaDateUS(jdDigitacao.getDate()));
        } catch (Exception ex) {
            modelNF.setDataDigitacao(new Date());
        }
        try {
            modelNF.setDataEmissao(bLMascaras.converterDataParaDateUS(jdEmissao.getDate()));
        } catch (Exception ex) {
            modelNF.setDataEmissao(new Date());
        }
        try {
            modelNF.setDataCancelamento(bLMascaras.converterDataParaDateUS(jdCancelamento.getDate()));
        } catch (Exception ex) {
            modelNF.setDataCancelamento(new Date());
        }
        modelNF.setDocCliente(null);
        modelNF.setEmpresa(controllerEmpresa.getEmpresaController(jtfEmpresa.getText()).getEmpresa().getCodigo());
        //verificar
        modelNF.setFinNfe(null);
        modelNF.setIcmsBc(Double.parseDouble(jtfICMSBC.getText()));
        modelNF.setIcmsVlr(Double.parseDouble(jtfICMSVlr.getText()));
        modelNF.setIpiBc(Double.parseDouble(jtfIPIBC.getText()));
        modelNF.setIpiVlr(Double.parseDouble(jtfIPIVlr.getText()));
        modelNF.setModelonfe(jtfMod.getText());
        //verificar
        modelNF.setMotivoNfe(null);
        //verificar
        modelNF.setNomeDocumento(null);
        //verificar
        modelNF.setNumNfeDev(null);
        try {
            modelNF.setNumNfeFat(new BigDecimal(jtfNumeroNFEFat.getText()));
        } catch (Exception e) {
            modelNF.setNumNfeFat(new BigDecimal(0));
        }
        try {
            modelNF.setNumeroNfe(new BigDecimal(jtfNNFeNFCe.getText()));
        } catch (Exception e) {
            modelNF.setNumeroNfe(new BigDecimal(0));
        }
        modelNF.setPedido(Integer.parseInt(jcbNPedido.getSelectedItem().toString()));
        modelNF.setPedidoCliente(jcbNPedido.getSelectedItem().toString());
        modelNF.setPedidoInterno(null);
        modelNF.setPesoVolume(Double.parseDouble(jtfPesoVolumes.getText()));
        modelNF.setPisBc(Double.parseDouble(jtfPisBC.getText()));
        modelNF.setPisVlr(Double.parseDouble(jtfPISVlr.getText()));
        modelNF.setPlacaVeiculo(jtfPlaca.getText());
        //verificar
        modelNF.setQrcode(null);
        try {
            modelNF.setQtdeVolume(Integer.parseInt(jtfQtVolumes.getText()));
        } catch (Exception e) {
            modelNF.setQtdeVolume(0);
        }
        //verificar
        modelNF.setRefnfe(null);
        modelNF.setSerieNfe(jtfSerie.getText());
        //verificar
        modelNF.setStatusNfe(null);
        //verificar
        modelNF.setTpamb(null);
        //verificar
        modelNF.setTpemis(null);
        modelNF.setUfPlaca(jtfUFPlaca.getSelectedItem().toString());
        modelNF.setValorDescontos(Double.parseDouble(jtfDescontoProdutos.getText()));
        modelNF.setValorProdutos(Double.parseDouble(jtfValorTotalprodutos.getText()));
        modelNF.setValorTotal(Double.parseDouble(jtfValorBrutoProdutos.getText()));
        modelNF.setVtotibpt(0);
        modelNF.setVtottrib(0);
        if (controllerNF.salvarNFController(modelNF) > 0) {
            JOptionPane.showMessageDialog(this, "Registro gravado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao gravar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jcbNomeClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbNomeClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (this.jcbNomeCliente.isPopupVisible()) {
            this.retornarClientePeloNome(jcbNomeCliente.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jcbNomeClientePopupMenuWillBecomeInvisible

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limparTela();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbGerarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGerarXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGerarXMLActionPerformed

    private void preencherFormulario() {
        setarImposto();
        modelVendas = VendaController.getVendasController(Integer.parseInt(jcbNPedido.getSelectedItem().toString()));
        //setar dados no formulario
        jcbCodigoCliente.setSelectedItem(String.valueOf(modelVendas.getClientesCodigo()));
        jcbFormaPagamento.setSelectedItem(controllerFormaPagamento.getFormaPagamentoController(modelVendas.getTipoPagamento()));
        retornarClientePeloCodigo(modelVendas.getClientesCodigo());
        //recupera os dados do pedido para adicionar ao estoque
        this.recuperarPedido(modelVendas.getCodigo());
        modelEmpresa = new Empresa();
        modelEmpresa = controllerEmpresa.getEmpresaController(1).getEmpresa();
        jtfEmpresa.setText(modelEmpresa.getRazaoSocial());
    }

    private int recuperarPedido(int pCodigo) {
        try {
            int codigoProduto;
            float quantidadeVolumes = 0, peso = 0;
            modelVendas.setCodigo(pCodigo);
            //recupera os dados do banco
            modelVendas = VendaController.getVendasController(pCodigo);
            //seta os dados na interface
            this.jtfDescontoProdutos.setText(String.valueOf(modelVendas.getDesconto()));
            this.jtfValorTotalprodutos.setText(String.valueOf(modelVendas.getValorTotal()));
            this.jtfValorBrutoProdutos.setText(String.valueOf(modelVendas.getValorTotal() + modelVendas.getDesconto()));
            this.jcbFormaPagamento.setSelectedItem(controllerTipoPagamento.getFormaPagamentoController(modelVendas.getTipoPagamento()).getDescricao());
            //recupera os dados do banco
            listaVendaAlterar = VendaController.getListaVendasController(pCodigo);
            //carregar lista de produtos da venda
            DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
            modelo.setNumRows(0);

            int cont = listaVendaAlterar.size();
            for (int i = 0; i < cont; i++) {
                codigoProduto = listaVendaAlterar.get(i).getProdutosCodigo();
                modelProdutos = controllerProdutos.getProdutosController(codigoProduto);
                quantidadeVolumes += listaVendaAlterar.get(i).getQuantidade();
                peso += modelProdutos.getPeso() * listaVendaAlterar.get(i).getQuantidade();
                modelo.addRow(new Object[]{
                    listaVendaAlterar.get(i).getProdutosCodigo(),
                    modelProdutos.getNome(),
                    listaVendaAlterar.get(i).getQuantidade(),
                    listaVendaAlterar.get(i).getValor(),
                    listaVendaAlterar.get(i).getQuantidade() * listaVendaAlterar.get(i).getValor()
                });
            }
            jtfQtVolumes.setText(quantidadeVolumes + "");
            jtfPesoVolumes.setText(peso + "");
            jdDigitacao.setDate(bLMascaras.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
            jdEmissao.setDate(bLMascaras.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
            return modelVendas.getClientesCodigo();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);
            return 0;
        }
    }

    /**
     *
     * @param pClienteCodigo 0 - busca o cliente baseado no combobox codigo
     * cliente
     */
    private void retornarClientePeloCodigo(int pCodigo) {
        modelCliente = controllerCliente.getClienteController(pCodigo);
        jcbNomeCliente.setSelectedItem(modelCliente.getNome());
    }

    private void retornarClientePeloNome(String pNome) {
        modelCliente = controllerCliente.getClienteController(pNome);
        jcbCodigoCliente.setSelectedItem(modelCliente.getCodigo() + "");
    }

    private void listarCodigoVendas() {
        listaVendaes = VendaController.getListaPedidosController();
        jcbNPedido.removeAllItems();
        for (int i = 0; i < listaVendaes.size(); i++) {
            jcbNPedido.addItem(listaVendaes.get(i).getCodigo());
        }
    }

    private void listarFormaPagamento() {
        listaFormaPagamentos = controllerFormaPagamento.getListaFormaPagamentoController();
        jcbFormaPagamento.removeAllItems();
        for (int i = 0; i < listaFormaPagamentos.size(); i++) {
            jcbFormaPagamento.addItem(listaFormaPagamentos.get(i).getDescricao());
        }
    }

    private void listarBancos() {
        listaBancos = controllerBanco.getListaBancoController();
        jcbBanco.removeAllItems();
        for (int i = 0; i < listaBancos.size(); i++) {
            jcbBanco.addItem(listaBancos.get(i).getNomeReduzido());
        }
    }

    private void listarClientes() {
        listaClientes = controllerCliente.getListaClienteAtivoController();
        jcbCodigoCliente.removeAllItems();
        jcbNomeCliente.removeAllItems();
        for (int i = 0; i < listaClientes.size(); i++) {
            jcbNomeCliente.addItem(listaClientes.get(i).getNome());
            jcbCodigoCliente.addItem(listaClientes.get(i).getCodigo() + "");
        }
    }

    private void carregarTransportadora() {
        listaTransportadoras = controllerTransportadora.getListaTransportadoraController();
        jcbCodigoTransportadora.removeAllItems();
        jcbTransportadora.removeAllItems();
        for (int i = 0; i < listaTransportadoras.size(); i++) {
            jcbTransportadora.addItem(listaTransportadoras.get(i).getNome());
            jcbCodigoTransportadora.addItem(listaTransportadoras.get(i).getCodigo() + "");
        }
    }

    /**
     * Soma e atualiza os valores total
     *
     * @return
     */
    private float somaEAtualizaValorTotal() {
        float soma = 0, valor = 0, desconto = 0;
        int cont = tbProdutos.getRowCount();
        //pegar valor desconto
        try {
            desconto = Float.parseFloat(jtfDescontoProdutos.getText());
        } catch (Exception e) {
            desconto = 0;
        }
        for (int i = 0; i < cont; i++) {
            valor = Float.parseFloat(String.valueOf(tbProdutos.getValueAt(i, 4)));
            soma = valor + soma;
        }
        soma = soma - desconto;
        return bLMascaras.arredondamentoComPontoDuasCasas(soma);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNFe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNFe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNFe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNFe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewNFe().setVisible(true);
            }
        });
    }

    private void setarImposto() {
        jtfCofinsBC.setText("0");
        jtfCofinsVlr.setText("0");
        jtfICMSBC.setText("0");
        jtfICMSVlr.setText("0");
        jtfIPIBC.setText("0");
        jtfIPIVlr.setText("0");
        jtfPISVlr.setText("0");
        jtfPisBC.setText("0");
    }

    private void limparTela() {
        //carregar lista de produtos da venda
        DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
        modelo.setNumRows(0);
        jcbNPedido.setSelectedIndex(0);
        jtfChave.setText("");
        jtfQtVolumes.setText("");
        jtfChaveNFeR.setText("");
        jtfCofinsBC.setText("0");
        jtfCofinsVlr.setText("0");
        jtfDadosAdicionais.setText("");
        jtfDescontoProdutos.setText("");
        jtfEmpresa.setText("");
        jtfICMSBC.setText("0");
        jtfICMSVlr.setText("0");
        jtfIPIBC.setText("0");
        jtfIPIVlr.setText("0");
        jtfMod.setText("");
        jtfNNFeNFCe.setText("");
        jtfNPedido.setText("");
        jtfNumeroNFEFat.setText("");
        jtfPISVlr.setText("0");
        jtfPesoVolumes.setText("");
        jtfPisBC.setText("0");
        jtfPlaca.setText("");
        jtfValorBrutoProdutos.setText("");
        jtfValorTotalprodutos.setText("");
        listarCodigoVendas();
        listarFormaPagamento();
        listarClientes();
        carregarTransportadora();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbGerarXML;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbBanco;
    private javax.swing.JComboBox<String> jcbCodigoCliente;
    private javax.swing.JComboBox<String> jcbCodigoTransportadora;
    private javax.swing.JComboBox<String> jcbFiltro;
    private javax.swing.JComboBox<String> jcbFormaPagamento;
    private javax.swing.JComboBox<String> jcbTipoNFe;
    private javax.swing.JComboBox<String> jcbTransportadora;
    private com.toedter.calendar.JDateChooser jdCancelamento;
    private com.toedter.calendar.JDateChooser jdDigitacao;
    private com.toedter.calendar.JDateChooser jdEmissao;
    private javax.swing.JTable jtNfe;
    private javax.swing.JTextField jtfChave;
    private javax.swing.JTextField jtfChaveNFeR;
    private javax.swing.JTextField jtfCofinsBC;
    private javax.swing.JTextField jtfCofinsVlr;
    private javax.swing.JTextField jtfDadosAdicionais;
    private javax.swing.JTextField jtfDescontoProdutos;
    private javax.swing.JTextField jtfEmpresa;
    private javax.swing.JTextField jtfICMSBC;
    private javax.swing.JTextField jtfICMSVlr;
    private javax.swing.JTextField jtfIPIBC;
    private javax.swing.JTextField jtfIPIVlr;
    private javax.swing.JTextField jtfMod;
    private javax.swing.JTextField jtfNNFeNFCe;
    private javax.swing.JTextField jtfNPedido;
    private javax.swing.JTextField jtfNumeroNFEFat;
    private javax.swing.JTextField jtfPISVlr;
    private javax.swing.JTextField jtfPesoVolumes;
    private javax.swing.JTextField jtfPisBC;
    private javax.swing.JTextField jtfPlaca;
    private javax.swing.JTextField jtfQtVolumes;
    private javax.swing.JTextField jtfSerie;
    private javax.swing.JTextField jtfTextoPesquisar;
    private javax.swing.JComboBox<String> jtfUFPlaca;
    private javax.swing.JTextField jtfValorBrutoProdutos;
    private javax.swing.JTextField jtfValorTotalprodutos;
    private javax.swing.JTable tbProdutos;
    // End of variables declaration//GEN-END:variables

    class configNfeFacil implements Serializable {

        String url, usuario, senha;
        String driver = "";  //"sun.jdbc.odbc.JdbcOdbcDriver";
        String banco = "";  //"jdbc:odbc:portonfe";
        String caminho_conexao = "";
        String caminho_nfeprot = "";  //"NFEPROT";
        String caminho_assinatura = "";  //"ASSINADA";
        String caminho_consulta = "";  //"ASSINADA";
        String caminho_ler_assinar = "";  //"ASSINAR";
        String caminho_txt = "";  //"TXT";
        String caminho_grava_assinar = "";  //"ASSINAR";
        String caminho_grava_assinada = "";  //"ASSINADA";
        String caminho_grava_retconsu = "";  //"RETCONSU";
        String caminho_grava_retcanc = "";  //"RETCANCE";
        String caminho_grava_retcorr = "";  //"RETCORRI";
        String caminho_grava_retinut = "";  //"RETINUTI";
        String caminho_grava_retlote = "";  //"RETLOTE";
        String caminho_grava_retrecep = "";  //"RETRECEP";
        String caminho_grava_inut = "";  //"INUTILIZ";
        String caminho_grava_canc = "";  //"CANCELA";
        String caminho_grava_corr = "";  //"CORRIGE";
        String caminho_grava_impDanfe = "";  //"IMPDANFE";
        String file_keystore = "";  //"certificado.pfx";
        String file_truststore = "";  //"NFeCacerts"  //"cartificado.jks";
        String senha_config = "";
    }

    class config_fatura implements Serializable {

        String usuario = "";
        String senha = "";
        String local = "";
        String driver = "";
        String jdbc = "";
        String bd = "";
    }

}
